[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Nola](https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/)

Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

```
# nola
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
```

---

In [15]:
import numpy as np
odd_seq = np.linspace(1, 63, 32)
odd_seq

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63.])

In [16]:
nola = np.resize(odd_seq, (4,8))[:,:-1]
nola

array([[ 1.,  3.,  5.,  7.,  9., 11., 13.],
       [17., 19., 21., 23., 25., 27., 29.],
       [33., 35., 37., 39., 41., 43., 45.],
       [49., 51., 53., 55., 57., 59., 61.]])

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/solution/)