[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Roux](https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/)

Define a *roux* array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.

**Examples**  

```
# roux array of length 5
[9 0 4 0 1]
```

```
# roux array of length 8
[ 0 16  0  9  0  4  0  1]
```

```
# roux array of length 12
[ 0 36  0 25  0 16  0  9  0  4  0  1]
```

**Note**: odd-length arrays begin with a square number while even-length arrays begin with a zero.

Implement a function called `make_roux(n)` that inputs `n`, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above.

---

In [9]:
n = 5
import numpy as np
squares = np.array([i+1 for i in range(-(n//-2))]) # upside down floor division, i.e. ceil, ceil(5,2) = 3
zeros = np.zeros((n//2))
squares

array([1, 2, 3])

In [10]:
roux = np.empty((squares.size + zeros.size))
roux[0::2] = squares**2
roux[1::2] = zeros
roux[::-1]

array([9., 0., 4., 0., 1.])

In [13]:
import numpy as np

def make_roux(n):
    """returns a roux array of length n"""
    squares = np.array([i+1 for i in range(-(n//-2))])
    zeros = np.zeros((n//2))
    roux = np.empty((squares.size + zeros.size))
    roux[0::2] = squares**2
    roux[1::2] = zeros
    return roux[::-1].astype('int')

for n in [5,8,12]:
    print(f"Roux array, n = {n}: {make_roux(n)}")

Roux array, n = 5: [9 0 4 0 1]
Roux array, n = 8: [ 0 16  0  9  0  4  0  1]
Roux array, n = 12: [ 0 36  0 25  0 16  0  9  0  4  0  1]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/solution/)