[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Big Fish](https://www.practiceprobs.com/problemsets/python-numpy/proficient/big-fish/)

10 fish occupy a 5x5x5 grid of water 🐟. Each fish decides to move to a new (i,j,k) location given by the 2-d array below. If multiple fish end up occupying the same cell, the biggest fish eats the smaller fish. Determine which fish survive.

In [2]:
import numpy as np

locs = np.array([
    [0,0,0],
    [1,1,2],
    [0,0,0],
    [2,1,3],
    [5,5,4],
    [5,0,0],
    [5,0,0],
    [0,0,0],
    [2,1,3],
    [1,3,1]
])

generator = np.random.default_rng(1010)
weights = generator.normal(size=10)

print(weights)
# [-1.699  0.538 -0.226 -1.09   0.554 -1.501  0.445  1.345 -1.124  0.212]

[-1.69870017  0.53799701 -0.22561399 -1.09020894  0.55391264 -1.50115445
  0.44545933  1.3448172  -1.12364327  0.21216015]


---

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
weights_nrm = mms.fit_transform(weights[:, np.newaxis]).ravel() # 0 --> 1  normalized

### Using dictionaries

In [4]:
fish = {i:{"loc": locs[i],
           "weight_nrm": weights_nrm[i],
           "alive": True} for i in range(len(locs))}
[v for v in fish.values()]

[{'loc': array([0, 0, 0]), 'weight_nrm': 0.0, 'alive': True},
 {'loc': array([1, 1, 2]), 'weight_nrm': 0.7349053440345731, 'alive': True},
 {'loc': array([0, 0, 0]), 'weight_nrm': 0.48400781250074065, 'alive': True},
 {'loc': array([2, 1, 3]), 'weight_nrm': 0.1999302635044849, 'alive': True},
 {'loc': array([5, 5, 4]), 'weight_nrm': 0.740134700172978, 'alive': True},
 {'loc': array([5, 0, 0]), 'weight_nrm': 0.06490704591887986, 'alive': True},
 {'loc': array([5, 0, 0]), 'weight_nrm': 0.704500497499297, 'alive': True},
 {'loc': array([0, 0, 0]), 'weight_nrm': 0.9999999999999999, 'alive': True},
 {'loc': array([2, 1, 3]), 'weight_nrm': 0.1889448416205302, 'alive': True},
 {'loc': array([1, 3, 1]), 'weight_nrm': 0.6278460377532108, 'alive': True}]

In [5]:
for i, fi in fish.items():
    for j, fj in fish.items():
        if np.array_equal(fi['loc'],fj['loc']) & (i != j):
            died = ''
            if fi['weight_nrm'] > fj['weight_nrm']:
                fj['alive'] = False
                died = f'fish j = {j} died'
            else:
                fi['alive'] = False
                died = f'fish i = {i} died'
            print(f"same loc: {i,j}, {fi['weight_nrm']} {fj['weight_nrm']} {died}.")

same loc: (0, 2), 0.0 0.48400781250074065 fish i = 0 died.
same loc: (0, 7), 0.0 0.9999999999999999 fish i = 0 died.
same loc: (2, 0), 0.48400781250074065 0.0 fish j = 0 died.
same loc: (2, 7), 0.48400781250074065 0.9999999999999999 fish i = 2 died.
same loc: (3, 8), 0.1999302635044849 0.1889448416205302 fish j = 8 died.
same loc: (5, 6), 0.06490704591887986 0.704500497499297 fish i = 5 died.
same loc: (6, 5), 0.704500497499297 0.06490704591887986 fish j = 5 died.
same loc: (7, 0), 0.9999999999999999 0.0 fish j = 0 died.
same loc: (7, 2), 0.9999999999999999 0.48400781250074065 fish j = 2 died.
same loc: (8, 3), 0.1889448416205302 0.1999302635044849 fish i = 8 died.


In [25]:
print("Remaining Fish:")
[i for i in range(len(locs)) if fish[i]['alive']]

Remaining Fish:


[1, 3, 4, 6, 7, 9]

### Numpy and vector based

In [29]:
loc_coinc = (locs[:,None] == locs).all(-1) * 1 # broadcast each loc to every loc similar to outer; true if all coords are true
print(loc_coinc)

[[1 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [31]:
big_fish = (weights_nrm[:,None] > weights_nrm) * 1 # outer, but greater than
print(big_fish)

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 1 0 1 1]
 [1 0 0 1 0 1 0 0 1 0]
 [1 0 0 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 1 0 1 1]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 1 1]
 [1 1 1 1 1 1 1 0 1 1]
 [1 0 0 0 0 1 0 0 0 0]
 [1 0 1 1 0 1 0 0 1 0]]


In [30]:
big_fish * loc_coinc

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# aborting direction, which is only simple for two coincident fish

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/proficient/big-fish/solution/)