[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Movie Ratings](https://www.practiceprobs.com/problemsets/python-numpy/proficient/movie-ratings/)

You’re given a 10x2 array of floats where each row represents a movie. The first column represents the movie’s rating and the second column represents the director’s rating.

In [1]:
import numpy as np

generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan

print(ratings)
# [[ 7.  1.]
#  [nan  2.]
#  [nan  8.]
#  [ 9.  3.]
#  [ 8.  9.]
#  [ 5.  2.]
#  [ 8.  2.]
#  [nan  6.]
#  [ 9.  2.]
#  [nan  5.]]

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


Create a third column that represents the overall rating. The overall rating is equal to the movie rating if it exists, otherwise the director’s rating.

---

In [5]:
ratings = np.pad(ratings, ((0,0),(0,1))) # increase dim 1 by 1 step at the end

In [6]:
for i in range(len(ratings)):
    if np.isnan(ratings[i][0]):
        ratings[i][2] = ratings[i][1]
    else:
        ratings[i][2] = ratings[i][0]
print(ratings)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/proficient/movie-ratings/solution/)