[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Taco Truck](https://www.practiceprobs.com/problemsets/python-numpy/proficient/taco-truck/)

You own a taco truck that’s open 24/7 and manage five employees who run it. Employees work solo, eight-hour shifts. You decide the best way to set their schedule for the upcoming week is to create a bunch of random schedules and select one that looks best.

You build a 1000x21 array of random employee ids where element (i,j) gives the employee id working shift j for schedule i.

In [ ]:
import numpy as np

generator = np.random.default_rng(999)
schedules = generator.integers(low=0, high=5, size=(1000, 21))

print(schedules)
# [[4 3 0 ... 2 0 0]
#  [2 4 3 ... 3 3 2]
#  [1 0 1 ... 1 2 1]
#  ...
#  [2 2 1 ... 3 1 4]
#  [1 0 3 ... 2 3 2]
#  [1 1 4 ... 2 4 2]]

A Schedule is *valid* as long as no employee works two consecutive shifts. Get the row indices of all *valid* schedules.

---

In [ ]:
# valid schedules - i axis (0)
# undefined question - 


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/proficient/taco-truck/solution/)