[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Taco Truck](https://www.practiceprobs.com/problemsets/python-numpy/proficient/taco-truck/)

You own a taco truck that’s open 24/7 and manage five employees who run it. Employees work solo, eight-hour shifts. You decide the best way to set their schedule for the upcoming week is to create a bunch of random schedules and select one that looks best.

You build a 1000x21 array of random employee ids where element (i,j) gives the employee id working shift j for schedule i.

In [1]:
import numpy as np

generator = np.random.default_rng(999)
schedules = generator.integers(low=0, high=5, size=(1000, 21))

print(schedules)
# [[4 3 0 ... 2 0 0]
#  [2 4 3 ... 3 3 2]
#  [1 0 1 ... 1 2 1]
#  ...
#  [2 2 1 ... 3 1 4]
#  [1 0 3 ... 2 3 2]
#  [1 1 4 ... 2 4 2]]

[[4 3 0 ... 2 0 0]
 [2 4 3 ... 3 3 2]
 [1 0 1 ... 1 2 1]
 ...
 [2 2 1 ... 3 1 4]
 [1 0 3 ... 2 3 2]
 [1 1 4 ... 2 4 2]]


A Schedule is *valid* as long as no employee works two consecutive shifts. Get the row indices of all *valid* schedules.

---

In [16]:
# valid schedules - i axis (0) - if no consecutive values
# shift j covers entire week,  3 per day, 7 days: 21 shifts

# use np diff -> if 0 it implies the same value
# test example:
def test_schedule_example(schedules, idx):
    print(f"Schedule {idx}:", schedules[idx])
    print(f"Diff {idx}:", np.diff(schedules[idx,], 1, axis=0))

test_schedule_example(schedules, 0)
sch_diff = np.diff(schedules, 1, axis=1)

# check all i schedules for 0's
valid_idxs = []
is_valids = []
for i in range(len(sch_diff)):
    is_valid = not (sch_diff[i,:] == 0).any()
    is_valids.append(is_valid)
    if is_valid:
        valid_idxs.append(i)
print("Valid Schedule Indicies:", valid_idxs)

Schedule 0: [4 3 0 0 0 3 0 3 0 0 0 4 0 0 4 3 2 4 2 0 0]
Diff 0: [-1 -3  0  0  3 -3  3 -3  0  0  4 -4  0  4 -1 -1  2 -2 -2  0]
Valid Schedule Indicies: [25, 138, 188, 289, 375, 426, 533, 886, 975, 982]


In [17]:
# visual check on results
for idx in valid_idxs:
    test_schedule_example(schedules, idx)

Schedule 25: [1 4 1 4 2 4 3 4 0 1 2 3 0 3 1 2 1 2 0 4 0]
Diff 25: [ 3 -3  3 -2  2 -1  1 -4  1  1  1 -3  3 -2  1 -1  1 -2  4 -4]
Schedule 138: [0 4 3 0 4 3 0 4 3 4 1 2 4 0 1 4 1 0 3 2 0]
Diff 138: [ 4 -1 -3  4 -1 -3  4 -1  1 -3  1  2 -4  1  3 -3 -1  3 -1 -2]
Schedule 188: [2 4 0 1 0 2 1 2 4 1 3 1 0 2 0 3 0 3 0 2 1]
Diff 188: [ 2 -4  1 -1  2 -1  1  2 -3  2 -2 -1  2 -2  3 -3  3 -3  2 -1]
Schedule 289: [0 3 1 4 2 1 4 2 4 1 0 4 1 0 4 2 4 3 0 3 1]
Diff 289: [ 3 -2  3 -2 -1  3 -2  2 -3 -1  4 -3 -1  4 -2  2 -1 -3  3 -2]
Schedule 375: [0 4 3 1 2 3 4 3 1 2 1 2 0 2 0 3 2 0 3 1 4]
Diff 375: [ 4 -1 -2  1  1  1 -1 -2  1 -1  1 -2  2 -2  3 -1 -2  3 -2  3]
Schedule 426: [1 0 2 0 2 3 2 3 4 1 2 4 3 4 0 4 1 0 2 1 2]
Diff 426: [-1  2 -2  2  1 -1  1  1 -3  1  2 -1  1 -4  4 -3 -1  2 -1  1]
Schedule 533: [2 1 4 1 3 0 4 1 2 3 4 3 0 3 4 3 1 3 1 2 3]
Diff 533: [-1  3 -3  2 -3  4 -3  1  1  1 -1 -3  3  1 -1 -2  2 -2  1  1]
Schedule 886: [3 4 3 0 4 1 0 4 1 4 1 3 1 3 4 3 1 2 3 4 0]
Diff 886: [ 1 -1 -3  4 -3 -1  4 -3

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/proficient/taco-truck/solution/)