[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Pyscho Parent](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/)

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy . You represent the field as a 10x10 array of 0s.

In [1]:
import numpy as np

field = np.zeros(shape = (10, 10))

print(field)
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Insert 20 random normal values at random (non repeating) locations in the grid. Then you'll know how much candy to hide at each spot.

---

In [23]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
rnd = np.random.default_rng(42)

p_grid = rnd.normal(0, 1, (100))
p_grid = mms.fit_transform(p_grid[:, np.newaxis]).ravel()

cdy_idxs = np.zeros(100)
cdy_idxs[rnd.choice(100, size=20, replace=False)] = 1 # set 20 randomly selected entries to 1; acts as a mask
cdy_field = np.reshape(np.round(p_grid, 3) * cdy_idxs, (10,10))
print(cdy_field)

[[0.    0.    0.    0.    0.    0.    0.    0.399 0.    0.268]
 [0.    0.    0.493 0.    0.    0.    0.    0.    0.    0.   ]
 [0.432 0.31  0.775 0.    0.    0.391 0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.271 0.    0.   ]
 [0.658 0.    0.314 0.    0.505 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.62  0.    0.    0.392 0.364 0.    0.43 ]
 [0.165 0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.315 0.    0.    0.    0.    0.362 0.48  0.    0.   ]
 [0.    0.    0.    0.    0.    0.123 0.    0.    0.    0.   ]]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/solution/)