[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Neural Network Convolution](https://www.practiceprobs.com/problemsets/python-numpy/expert/neural-network-convolution/)

Suppose you have a 2-D array, `arr`,

In [1]:
import numpy as np

arr = np.array([
    [0.15, 0.71, 0.26, -0.11, -2.03],
    [0.13, 0.44, -0.11, -0.23, 0.19],
    [-1.44, 0.51, 0.42, 2.58, -0.88],
    [-1.18, 2.73, 2.35, 0.21, -0.29],
    [-1.64, -0.37, 0.27, 0.57, 1.82]
])

and another, smaller 2-D array, `filter`,

In [2]:
filter = np.array([
    [0.08, 0.27, -0.24],
    [-0.25, -0.11, -0.18],
    [0.44, 1.87, 1.18]
])

In the context of neural networks, a convolution works by "sliding" `filter` over `arr` in row major order (left to right, top to bottom), taking the dot product between `filter` and the portion of `arr` it covers at each step.

![](https://www.practiceprobs.com/problemsets/python-numpy/images/convolution.gif)

The result of all these dot products is the following 3x3 array.

```
[[ 0.9   4.15  4.47]
 [ 7.74  5.27  0.74]
 [-1.6  -0.43  3.72]]
```

In [3]:
# cross check above for 2D pre-sanity check
# using loops:
i_steps = arr.shape[0] - filter.shape[0] + 1
j_steps = arr.shape[1] - filter.shape[1] + 1
conv = np.zeros((i_steps,j_steps))

for istep in range(i_steps):
    for jstep in range(j_steps):
        # create dot product
        recp_field = arr[istep:istep+filter.shape[0],
                         jstep:jstep+filter.shape[1]]
        conv[istep,jstep] = np.sum(recp_field * filter)
print(np.round(conv,2))

[[ 0.9   4.15  4.47]
 [ 7.74  5.27  0.74]
 [-1.6  -0.43  3.72]]


In [4]:
# using sliding windows:
from numpy.lib.stride_tricks import sliding_window_view

recp_field = sliding_window_view(arr, window_shape=filter.shape)
conv = np.einsum('ij,ijkl->kl', filter, recp_field)
print(np.round(conv,2))


[[ 0.9   4.15  4.47]
 [ 7.74  5.27  0.74]
 [-1.6  -0.43  3.72]]


Now suppose `arr` is the following 33x33x3 array.

In [5]:
import numpy as np
np.printoptions(width=100)
rng = np.random.default_rng(123)
arr = rng.normal(size=(33,33,3)).round(2)

print(arr)
# [
#     [[-0.99 -0.37  1.29]
#      [ 0.19  0.92  0.58]
#      [-0.64  0.54 -0.32]
#      ...
#      [ 1.23  0.15  0.48]
#      [-0.15  1.32 -1.22]
#      [-0.3  -1.17  0.83]]
# 
#     [[ 0.85 -0.52  1.66]
#      [-0.3  -1.38 -0.28]
#      [ 0.36 -0.23  2.27]
#      ...
#      [ 1.52  0.49  0.7 ]
#      [ 0.85 -0.91  0.12]
#      [ 0.15 -0.16 -1.09]]
# 
#     ...
# 
#     [[-0.38 -0.45  1.  ]
#      [-0.58  2.18  0.36]
#      [-0.44 -2.77  0.82]
#      ...
#      [-1.58 -0.5  -0.52]
#      [-0.86 -0.54 -0.26]
#      [ 0.23  0.81 -0.4 ]]
# 
#     [[-1.98 -0.22 -0.79]
#      [-0.01 -1.47 -0.83]
#      [-0.87  0.3  -0.82]
#      ...
#      [ 1.42  0.7  -0.75]
#      [-0.81  1.68 -0.82]
#      [-0.93  0.28 -1.61]]
# ]

[[[-0.99 -0.37  1.29]
  [ 0.19  0.92  0.58]
  [-0.64  0.54 -0.32]
  ...
  [ 1.23  0.15  0.48]
  [-0.15  1.32 -1.22]
  [-0.3  -1.17  0.83]]

 [[ 0.85 -0.52  1.66]
  [-0.3  -1.38 -0.28]
  [ 0.36 -0.23  2.27]
  ...
  [ 1.52  0.49  0.7 ]
  [ 0.85 -0.91  0.12]
  [ 0.15 -0.16 -1.09]]

 [[ 0.46 -1.66 -0.94]
  [-0.81 -0.41  0.84]
  [ 1.66  1.72  0.81]
  ...
  [-1.05  0.72 -0.9 ]
  [ 0.98  0.43  0.11]
  [-0.76  0.9   0.5 ]]

 ...

 [[-0.31 -0.05 -1.8 ]
  [-0.72  0.9   1.1 ]
  [ 0.92  1.25 -0.23]
  ...
  [ 1.25 -0.22 -0.19]
  [-0.76  1.64  1.18]
  [-0.99 -0.09  1.34]]

 [[-0.38 -0.45  1.  ]
  [-0.58  2.18  0.36]
  [-0.44 -2.77  0.82]
  ...
  [-1.58 -0.5  -0.52]
  [-0.86 -0.54 -0.26]
  [ 0.23  0.81 -0.4 ]]

 [[-1.98 -0.22 -0.79]
  [-0.01 -1.47 -0.83]
  [-0.87  0.3  -0.82]
  ...
  [ 1.42  0.7  -0.75]
  [-0.81  1.68 -0.82]
  [-0.93  0.28 -1.61]]]


And let `filter` be the following 5x5x3 array.

In [6]:
filter = rng.normal(size=(5,5,3)).round(2)

print(filter)
# [
#     [[-1.47  0.74  0.58]
#      [ 0.46  2.37  0.79]
#      [ 1.15 -1.11 -0.29]
#      [-0.98  0.29  0.44]
#      [-0.44 -0.03  0.69]]
# 
#     [[ 0.34  0.67 -0.11]
#      [-0.71 -1.   -0.88]
#      [ 0.61  0.49 -0.27]
#      [ 0.12 -1.56  0.11]
#      [ 0.32 -0.98  0.46]]
# 
#     [[-1.03  0.58  0.08]
#      [ 0.89  0.86  1.49]
#      [-0.4   0.86 -0.29]
#      [ 0.07 -0.09 -0.87]
#      [ 0.2   1.22 -0.27]]
# 
#     [[ 1.1  -2.61  1.64]
#      [-1.15  0.47  1.44]
#      [-1.45  0.39  1.37]
#      [ 0.13 -0.1   0.04]
#      [ 0.27  0.57  0.57]]
# 
#     [[-0.61 -0.41  0.93]
#      [ 1.47 -0.07 -0.29]
#      [ 0.49  1.02  0.2 ]
#      [ 0.16  0.95  0.52]
#      [ 1.11  0.13 -0.17]]
# ]

[[[-1.47  0.74  0.58]
  [ 0.46  2.37  0.79]
  [ 1.15 -1.11 -0.29]
  [-0.98  0.29  0.44]
  [-0.44 -0.03  0.69]]

 [[ 0.34  0.67 -0.11]
  [-0.71 -1.   -0.88]
  [ 0.61  0.49 -0.27]
  [ 0.12 -1.56  0.11]
  [ 0.32 -0.98  0.46]]

 [[-1.03  0.58  0.08]
  [ 0.89  0.86  1.49]
  [-0.4   0.86 -0.29]
  [ 0.07 -0.09 -0.87]
  [ 0.2   1.22 -0.27]]

 [[ 1.1  -2.61  1.64]
  [-1.15  0.47  1.44]
  [-1.45  0.39  1.37]
  [ 0.13 -0.1   0.04]
  [ 0.27  0.57  0.57]]

 [[-0.61 -0.41  0.93]
  [ 1.47 -0.07 -0.29]
  [ 0.49  1.02  0.2 ]
  [ 0.16  0.95  0.52]
  [ 1.11  0.13 -0.17]]]


Using strides of length two, calculate the convolution between these arrays. (The result should have shape 15x15.)

---

In [11]:
from numpy.lib.stride_tricks import sliding_window_view
import numpy as np

all_recp_fields = sliding_window_view(arr, filter.shape).transpose(3,4,5,0,1,2)
print(all_recp_fields.shape)
strided_recp_fields = all_recp_fields[:,:,:,::2,::2]
print(strided_recp_fields.shape)

(5, 5, 3, 29, 29, 1)
(5, 5, 3, 15, 15, 1)


In [12]:
conv = np.einsum('ijk,ijkpqr->pqr', filter, strided_recp_fields)
print(np.round(conv,2))

[[[  1.64]
  [ -3.22]
  [ -2.44]
  [  5.48]
  [  5.06]
  [-11.43]
  [ -0.57]
  [  3.01]
  [  3.34]
  [ -0.11]
  [  9.81]
  [-18.71]
  [ -5.59]
  [ -1.31]
  [ 11.43]]

 [[ -3.73]
  [ -3.17]
  [  3.46]
  [  6.59]
  [  3.09]
  [ -9.52]
  [ -5.96]
  [-17.02]
  [ -0.74]
  [  5.25]
  [ -5.24]
  [  0.94]
  [  5.98]
  [ -1.81]
  [ -9.84]]

 [[  6.67]
  [  5.45]
  [ -4.09]
  [ -7.73]
  [  0.46]
  [  7.22]
  [-13.19]
  [ -0.37]
  [ -4.16]
  [  1.67]
  [  5.93]
  [-11.28]
  [  3.95]
  [ -0.6 ]
  [ -0.14]]

 [[ -3.19]
  [ 10.18]
  [ -3.74]
  [ -1.82]
  [  5.39]
  [-11.1 ]
  [  7.43]
  [ 11.05]
  [ -9.48]
  [  7.  ]
  [ -6.42]
  [  2.44]
  [ -0.26]
  [  3.53]
  [ -2.11]]

 [[ -1.98]
  [ -4.43]
  [ 16.15]
  [  3.77]
  [ -2.17]
  [ 15.87]
  [ -8.11]
  [  3.58]
  [ 13.89]
  [ -2.95]
  [ -2.35]
  [  8.32]
  [-13.12]
  [  7.73]
  [  5.64]]

 [[ -8.34]
  [ -3.22]
  [ -5.11]
  [-11.67]
  [-12.48]
  [ 17.3 ]
  [  5.72]
  [ -1.  ]
  [  5.57]
  [  2.17]
  [ -9.02]
  [ -6.24]
  [ -0.12]
  [  9.1 ]
  [ -1.49]]

In [15]:
# given einsum, and potential for axes mix ups, I repeat the slow loop method
i_steps = arr.shape[0] - filter.shape[0] + 1
j_steps = arr.shape[1] - filter.shape[1] + 1
k_steps = arr.shape[2] - filter.shape[2] + 1
conv_chk = np.zeros((i_steps,j_steps,k_steps))

for istep in range(i_steps):
    for jstep in range(j_steps):
        for kstep in range(k_steps):
                
            # create dot product
            recp_field = arr[istep:istep+filter.shape[0],
                            jstep:jstep+filter.shape[1],
                            kstep:kstep+filter.shape[2]]
            conv_chk[istep,jstep,kstep] = np.sum(recp_field * filter)
print(np.round(
    conv_chk[::2,::2,::2][0] - conv[0]
    ,2)) # lazy stride step post calculation; diff equals zero, check :)

[[ 0.]
 [-0.]
 [ 0.]
 [-0.]
 [-0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-0.]
 [ 0.]
 [-0.]
 [ 0.]
 [-0.]]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/expert/neural-network-convolution/solution/)