[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [One-Hot-Encoding](https://www.practiceprobs.com/problemsets/python-numpy/expert/one-hot-encoding/)

Given a 1-D array of integers, [one-hot-encode](https://en.wikipedia.org/wiki/One-hot#Machine_learning_and_statistics) it into a 2-D array. In other words, convert this 1-D array called `yoyoyo`,

In [3]:
import numpy as np
yoyoyo = np.array([3, 1, 0, 1])

into a 2-D array like this.

```
# [[0. 0. 0. 1.]
#  [0. 1. 0. 0.]
#  [1. 0. 0. 0.]
#  [0. 1. 0. 0.]]
```

---

In [7]:
ohe = np.zeros((len(yoyoyo),np.max(yoyoyo)+1))
for i, yo in enumerate(yoyoyo):
    ohe[i,yo] = 1
print(ohe)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/expert/one-hot-encoding/solution/)