[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Outer Product](https://www.practiceprobs.com/problemsets/python-numpy/expert/outer-product/)

Calculate the element-wise [outer product](https://en.wikipedia.org/wiki/Outer_product) of two matrices, `A` & `B`.

In [1]:
import numpy as np

A = np.arange(10*3).reshape((10,3))
B = np.arange(10*5).reshape((10,5))

print(A)
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]
#  [12 13 14]
#  [15 16 17]
#  [18 19 20]
#  [21 22 23]
#  [24 25 26]
#  [27 28 29]]

print(B)
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]
#  [20 21 22 23 24]
#  [25 26 27 28 29]
#  [30 31 32 33 34]
#  [35 36 37 38 39]
#  [40 41 42 43 44]
#  [45 46 47 48 49]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


The result should be a 10x3x5 array where the ith 3x5 array is the outer product of Ai and Bi.

---

In [2]:
op = np.einsum('ij,ik->ijk', A, B)

In [7]:
# cross check single ith outer product
op_0 = np.outer(A[0],B[0])
op[0] == op_0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/expert/outer-product/solution/)