[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Table Tennis](https://www.practiceprobs.com/problemsets/python-numpy/expert/table-tennis/)

You manage a recreational table tennis league. There are 10 participants, and in an effort to make the first round of matchups as exciting as possible, you develop a model that predicts the score difference for every possible pair of players. That is, you produce a 10x10 matrix where (i,j) represents your prediction for player i’s score minus player j’s score if they were to compete.

In [1]:
import numpy as np

generator = np.random.default_rng(0)
score_diffs = np.round(generator.uniform(low=-15, high=15, size=(10,10)), 2)
np.fill_diagonal(score_diffs, np.nan)
score_diffs[np.triu_indices(10, k=1)[::-1]] = -score_diffs[np.triu_indices(10, k=1)]

print(score_diffs)
# [[   nan  -6.91 -13.77 -14.5    9.4   12.38   3.2    6.88   1.31  13.05]
#  [  6.91    nan  10.72 -13.99   6.89  -9.73  10.9    1.24  -6.01  -2.32]
#  [ 13.77 -10.72    nan   4.42   3.46  -3.49  14.92  14.43   5.57   4.51]
#  [ 14.5   13.99  -4.42    nan   0.76  -5.69  -0.42  11.68  13.02  -4.27]
#  [ -9.4   -6.89  -3.46  -0.76    nan  11.71  -8.19   3.7  -12.48   9.98]
#  [-12.38   9.73   3.49   5.69 -11.71    nan  -1.49   8.89  -8.08 -13.44]
#  [ -3.2  -10.9  -14.92   0.42   8.19   1.49    nan  13.26  -4.05 -11.84]
#  [ -6.88  -1.24 -14.43 -11.68  -3.7   -8.89 -13.26    nan  13.47  -1.2 ]
#  [ -1.31   6.01  -5.57 -13.02  12.48   8.08   4.05 -13.47    nan   6.87]
#  [-13.05   2.32  -4.51   4.27  -9.98  13.44  11.84   1.2   -6.87    nan]]

[[   nan  -6.91 -13.77 -14.5    9.4   12.38   3.2    6.88   1.31  13.05]
 [  6.91    nan  10.72 -13.99   6.89  -9.73  10.9    1.24  -6.01  -2.32]
 [ 13.77 -10.72    nan   4.42   3.46  -3.49  14.92  14.43   5.57   4.51]
 [ 14.5   13.99  -4.42    nan   0.76  -5.69  -0.42  11.68  13.02  -4.27]
 [ -9.4   -6.89  -3.46  -0.76    nan  11.71  -8.19   3.7  -12.48   9.98]
 [-12.38   9.73   3.49   5.69 -11.71    nan  -1.49   8.89  -8.08 -13.44]
 [ -3.2  -10.9  -14.92   0.42   8.19   1.49    nan  13.26  -4.05 -11.84]
 [ -6.88  -1.24 -14.43 -11.68  -3.7   -8.89 -13.26    nan  13.47  -1.2 ]
 [ -1.31   6.01  -5.57 -13.02  12.48   8.08   4.05 -13.47    nan   6.87]
 [-13.05   2.32  -4.51   4.27  -9.98  13.44  11.84   1.2   -6.87    nan]]


Given this matrix, determine the “best” schedule for round one - the schedule whose matchups minimize the sum of squared point differentials.

---

In [2]:
np.set_printoptions(suppress=True)

sq_diffs = score_diffs**2
sq_diffs[np.isnan(sq_diffs)] = 999
sq_diffs = sq_diffs.astype(np.float32)
print(np.round(sq_diffs,2))

[[999.    47.75 189.61 210.25  88.36 153.26  10.24  47.33   1.72 170.3 ]
 [ 47.75 999.   114.92 195.72  47.47  94.67 118.81   1.54  36.12   5.38]
 [189.61 114.92 999.    19.54  11.97  12.18 222.61 208.22  31.02  20.34]
 [210.25 195.72  19.54 999.     0.58  32.38   0.18 136.42 169.52  18.23]
 [ 88.36  47.47  11.97   0.58 999.   137.12  67.08  13.69 155.75  99.6 ]
 [153.26  94.67  12.18  32.38 137.12 999.     2.22  79.03  65.29 180.63]
 [ 10.24 118.81 222.61   0.18  67.08   2.22 999.   175.83  16.4  140.19]
 [ 47.33   1.54 208.22 136.42  13.69  79.03 175.83 999.   181.44   1.44]
 [  1.72  36.12  31.02 169.52 155.75  65.29  16.4  181.44 999.    47.2 ]
 [170.3    5.38  20.34  18.23  99.6  180.63 140.19   1.44  47.2  999.  ]]


In [10]:
from itertools import permutations
import math

# brute force all combinations
idxs = np.arange(10)
sum_sq_diffs = np.zeros((math.factorial(10))).astype(np.float32)
running_min_diff = np.inf
min_idxs = np.zeros((10), dtype=np.float32)
idx_comb = permutations(idxs, 10)

for i, comb in enumerate(idx_comb):
    sum_sq_diffs[i] = np.sum(sq_diffs[np.array(comb),idxs])
    if sum_sq_diffs[i] < running_min_diff:
        running_min_diff = sum_sq_diffs[i]
        min_idxs = np.array(comb, dtype=np.float32)
    # if i == 42: # for testing
    #     break

In [12]:
# results of brute force method
argmin = np.argmin(sum_sq_diffs)
min_sq_diff = sum_sq_diffs[argmin]
min_idxs

array([8., 7., 4., 6., 3., 2., 5., 9., 0., 1.], dtype=float32)

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/expert/table-tennis/solution/)